steps:
 # Build the container image
 - name: 'gcr.io/cloud-builders/docker'
   args: [ 'build', '-t', '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REGISTRY}/${_REPO}:$COMMIT_SHA', '.' ]
 # Push the container image to Container Registry
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REGISTRY}/${_REPO}:$COMMIT_SHA']
 # Deploy container image to Cloud Run
 - name: 'gcr.io/cloud-builders/gcloud'
   entrypoint: gcloud
   args:
   - 'run'
   - 'deploy'
   - '${_REPO}'
   - '--image'
   - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REGISTRY}/${_REPO}:$COMMIT_SHA'
   - '--region'
   - '${_REGION_CLOUD_RUN}'
   - '--allow-unauthenticated'
   - '--platform'
   - 'managed'
   - '--port'
   - '${_PORT}'
   - '--max-instances'
   - '1'
   - '--memory'
   - '128Mi'
   - '--set-env-vars'
   - 'DB_HOST=${_DB_HOST},DB_NAME=${_DB_NAME},DB_USER=${_DB_USER},DB_PASSWORD=${_DB_PASSWORD}'
images:
 - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REGISTRY}/${_REPO}'
 
substitutions:
  _PROJECT_ID: 'kim-s-resume'
  _REGISTRY: 'docker-repo'
  _REPO: 'stock-management-backend'
  _REGION: 'us-central1'
  _REGION_CLOUD_RUN: 'asia-southeast1'
  _PORT: '3000'

options:
  logging: CLOUD_LOGGING_ONLY